---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
      - edited
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: expaso/hassio-addons-workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: "hassos-addons"
      repository_edge: "hassos-addons-edge"
      repository_beta: "hassos-addons-beta"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
